version: 2
jobs:
  build-node-10:
    docker:
     - image: circleci/node:10.0.0
    working_directory: ~/indicative
    steps:
    - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: npm install
    - save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}
    - run: npm test

  build-node-latest:
    docker:
     - image: circleci/node:latest
    working_directory: ~/indicative
    steps:
    - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: npm install
    - save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}
    - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - build-node-latest
      - build-node-10
